version: '3.9'
services:
    lavalink:
        container_name: lavalink
        image: lavalink:latest
        ports:
            - '2333:2333'
        build:
            context: ./
            dockerfile: ./Lavalink/Dockerfile
        restart: always
    denver:
        container_name: denver
        image: denverspeaker:latest
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - lavalink
    dtogether:
        container_name: dtogether
        image: dtogether:latest
        ports:
            - '8080:8080'
        build:
            context: ./
            dockerfile: ./DiscordTogether/Dockerfile
        restart: always